# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PyProc PyPi

on:
  push:
    branches: [ master ]
  release:
    types:
      - published
  pull_request:
    branches: [ master ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python Version
      run: python -c "import sys; print(sys.version)"
    - name: Clean build directory
      run: rm -rf ./dists ./pyproc.egg-info ./tests/*.csv ./tests/*.idx ./*csv ./*idx
    - name: Test Package
      run: |
        pip install backoff
        python setup.py test
    - name: Build Package
      run: python setup.py sdist
    - name: Release to PyPi Test
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        repository_url: https://test.pypi.org/legacy/
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    - name: Release to PyPi
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
  
  
  
  
